dist: trusty
sudo: required
language: rust

addons:
    apt:
        packages:
            - libssl-dev

cache: cargo

rust:
    - 1.39.0
    - stable
    - beta
    - nightly

services: rabbitmq

script:
    - cargo build --verbose --all --all-features
    - cargo test  --verbose --all --all-features || RUST_LOG=lapin=trace cargo test --verbose --all --all-features

after_success: |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
        `RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --force cargo-tarpaulin`
        cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
    fi
